version: '3.3'

services:
  iperf3:
    image: networkstatic/iperf3:latest
    container_name: iperf3-server
    hostname: iperf3
    restart: always
	  network_mode: "host"
    security_opt:
      - no-new-privileges
	  command: -s
	  environment:
      - PUID=1000
      - PGID=1000
    ports:
      - '5201:5201'
